-- What is the total number of rows in each of the 3 table in the database? 
SELECT COUNT(*) AS Rows_of_customer FROM customer
SELECT COUNT(*) as Rows_of_prod_cat_info from prod_cat_info
SELECT COUNT(*) as Rows_of_transactions from transactions

-- Better way of doing
SELECT COUNT(*) AS Rows_of_customer FROM customer
UNION ALL
SELECT COUNT(*) as Rows_of_prod_cat_info from prod_cat_info
UNION ALL
SELECT COUNT(*) as Rows_of_transactions from transactions



-- What is the total number of transactions that have to return?  
SELECT COUNT(*)
FROM transactions
WHERE total_amt < 0;



/* 
	What is the time range of the transaction data available for analysis? 
	Show the output in number of days, months, and years simultaneously in different columns.
*/

SELECT 
	DATEDIFF(day, MIN(tran_date), MAX(tran_date)) AS Days,
	DATEDIFF(month, MIN(tran_date) , MAX(tran_date)) AS Months,
	DATEDIFF(year, MIN(tran_date), Max(tran_date)) AS Years
FROM transactions;



-- Which product category does the sub-category “DIY” belong to?
SELECT prod_cat 
FROM prod_cat_info
WHERE prod_subcat = 'DIY';



/*
	===> Data Analysis
*/

-- Which channel is most frequently used for transactions?
SELECT TOP 1 COUNT(store_type) AS most_freq_channel, store_type
FROM transactions
GROUP BY store_type
ORDER BY 1 DESC



-- What is the count of Male and Female customers in the database?
SELECT gender, COUNT(*) 
FROM customer
WHERE gender IS NOT NULL
GROUP BY gender 



-- From which city do we have the maximum number of customers and how many?
SELECT TOP 1 city_code, count(*) AS count_of_people
FROM customer
GROUP BY city_code
ORDER BY 2 DESC



-- How many sub-categories are there under the Books category?
SELECT COUNT(DISTINCT prod_subcat) AS No_of_sbu_category
FROM prod_cat_info
WHERE prod_cat = 'books'



-- What is the maximum quantity of products ever ordered?
SELECT MAX(qty) as Max_Qty
FROM transactions



-- What is the net total revenue generated in categories Electronics and Books?
SELECT sum(total_amt) AS total_revenue
FROM transactions AS t1
JOIN prod_cat_info AS t2
ON t1.prod_cat_code = t2.prod_cat_code and prod_cat IN ('electronics', 'books')



-- How many customers have more than 10 transactions with us, excluding returns?
SELECT COUNT(cust_id) AS customers_count 
FROM customer t1
JOIN transactions t2
ON t1.customer_Id = t2.cust_id 
WHERE total_amt > 0
GROUP BY cust_id
HAVING  COUNT(total_amt) > 10

-- This following query is most efficient because (JOINs are expensive (memory + CPU), especially with large datasets) 
SELECT COUNT(*) AS customers_count
FROM (
	SELECT cust_id 
	FROM transactions
	WHERE total_amt > 0
	GROUP BY cust_id
	HAVING COUNT(*) > 10
) sbq 



-- What is the combined revenue earned from the “Electronics” and “Clothing” categories, from “Flagship stores”?
SELECT SUM(total_amt) AS revenue
FROM prod_cat_info t1
JOIN transactions t2 ON t1.prod_cat_code = t2.prod_cat_code
WHERE prod_cat IN ('Electronics', 'Clothing') AND Store_type = 'Flagship store' AND total_amt > 0



/* What is the total revenue generated from “Male” customers in the “Electronics” category?
Output should display total revenue by product sub-category.*/

SELECT prod_subcat, SUM(total_amt) total_revenue 
FROM customer t1
JOIN transactions t2 ON t1.customer_Id = t2.cust_id
JOIN prod_cat_info t3 ON t2.prod_cat_code = t3.prod_cat_code
WHERE total_amt > 0 AND gender = 'M' AND prod_cat = 'electronics'
GROUP BY prod_subcat



-- What is the percentage of sales and returns by product sub-category; display only the top 5 sub-categories in terms of sales?
SELECT
	TOP 5
	prod_subcat,
	SUM(CASE WHEN total_amt > 0 THEN total_amt END) * 100.0 / (SELECT SUM(total_amt) FROM transactions WHERE total_amt > 0) total_sales, 
	SUM(CASE WHEN total_amt < 0 THEN total_amt END) * 100.0 / (SELECT SUM(total_amt) FROM transactions WHERE total_amt < 0) return_prod
FROM prod_cat_info t1
JOIN transactions t2 ON t1.prod_cat_code = t2.prod_cat_code
GROUP BY prod_subcat
ORDER BY 2 DESC



/* For all customers aged between 25 to 35 years, find the net total revenue generated by these consumers in the last 30 days 
of transactions from the maximum transaction date available in the data.*/

SELECT SUM(total_amt) AS net_total_revenue
FROM customer t1
JOIN transactions t2 ON t1.customer_Id = t2.cust_id
WHERE DATEDIFF(year, DOB, GETDATE()) BETWEEN 25 AND 35
  AND tran_date >= DATEADD(day, -30, (SELECT MAX(tran_date) FROM transactions))



-- Which product category has seen the max value of returns in the last 3 months of transactions?




-- Which store-type sells the maximum products; by value of sales amount and by quantity sold?
SELECT TOP 1 Store_type, SUM(total_amt) total_sales, SUM(qty) total_quantity
FROM transactions
WHERE total_amt > 0 AND qty > 0
GROUP BY Store_type
ORDER BY 2 DESC, 3 DESC



-- What are the categories for which average revenue is above the overall average.
SELECT prod_cat_code, AVG(total_amt) AS total_revenue 
FROM transactions
GROUP BY prod_cat_code
HAVING AVG(total_amt) > (SELECT AVG(total_amt) FROM transactions)


SELECT t1.prod_cat_code, prod_cat, AVG(total_amt) average
FROM prod_cat_info t1
JOIN transactions t2 ON t1.prod_cat_code = t2.prod_cat_code
GROUP BY t1.prod_cat_code, prod_cat
HAVING AVG(total_amt) > (SELECT AVG(total_amt) FROM transactions)
ORDER BY 3 DESC



/* Find the average and total revenue by each subcategory for the categories 
which are among top 5 categories in terms of quantity sold.*/

SELECT 
	prod_subcat_code, 
	AVG(total_amt) total_avg, 
	SUM(total_amt) total_revenue
FROM transactions
WHERE prod_cat_code IN (
	SELECT TOP 5 prod_cat_code 
	FROM transactions
	WHERE qty > 0
	GROUP BY prod_cat_code
	ORDER BY SUM(qty) DESC
)
GROUP BY prod_subcat_code